version: "3.8"

services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - SUBDOMAINS=${SUBDOMAINS}
      - TOKEN=${YOUR_DUCKDNS_TOKEN}
      - UPDATE_IP=ipv4
    restart: unless-stopped