version: "3.9"

services:
  youtrack:
    image: jetbrains/youtrack:2026.2.18194
    container_name: youtrack
    restart: unless-stopped

    volumes:
      - /srv/storage/NAS/docker-meta/youtrack/conf:/opt/youtrack/conf
      - /srv/storage/NAS/docker-meta/youtrack/data:/opt/youtrack/data
      - /srv/storage/NAS/docker-meta/youtrack/logs:/opt/youtrack/logs
      - /srv/storage/NAS/docker-meta/youtrack/backups:/opt/youtrack/backups

    networks:
      - proxy

    labels:
      - traefik.enable=true

      - traefik.http.routers.youtrack.rule=Host(`zhang-server-pc.duckdns.org`) && PathPrefix(`/you-track`)
      - traefik.http.routers.youtrack.entrypoints=websecure
      - traefik.http.routers.youtrack.tls.certresolver=letsencrypt

      - traefik.http.services.youtrack.loadbalancer.server.port=8080

      - traefik.http.middlewares.youtrack-strip.stripprefix.prefixes=/you-track
      - traefik.http.middlewares.youtrack-headers.headers.customrequestheaders.X-Forwarded-Prefix=/you-track

      - traefik.http.routers.youtrack.middlewares=youtrack-strip,youtrack-headers

networks:
  proxy:
    external: true