
version: "3.8"

services:
  valheim:
    image: lloesche/valheim-server:latest
    container_name: valheim-server
    user: "1000:1000"
    environment:
      - SERVER_NAME=Valheim Server
      - WORLD_NAME=MyWorld
      - SERVER_PASS=${PASSWORD}
      - SERVER_PORT=2456
      - PUBLIC=0
      - TZ=EST
    volumes:
      - /srv/storage/NAS/valheim-servers/server1:/config
    ports:
      - "2456-2458:2456-2458/udp"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G